routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/register', function () {
    return view('auth.login');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');


Route::resource('items', App\Http\Controllers\ItemController::class);


Route::resource('providers', App\Http\Controllers\ProviderController::class);


Route::resource('purchaseInvoices', App\Http\Controllers\PurchaseInvoiceController::class);


Route::resource('salesInvoices', App\Http\Controllers\SalesInvoiceController::class);

Route::get('sales/pdf', [App\Http\Controllers\PDFController::class, 'salesPDF'])->name('sales.pdf');
Route::get('sales/item/destroy', [App\Http\Controllers\SalesInvoiceController::class, 'destroyItem'])->name('sales.item.destroy');


Route::get('purchase/pdf', [App\Http\Controllers\PDFController::class, 'purchasePDF'])->name('purchase.pdf');
Route::get('purchaseinvoice/item/destroy', [App\Http\Controllers\PurchaseInvoiceController::class, 'destroyItem'])->name('purchase.item.destroy');
Route::get('export/excel', [App\Http\Controllers\SalesInvoiceController::class, 'exportExcel'])->name('sales.excel');
Route::get('export/purchase/excel', [App\Http\Controllers\PurchaseInvoiceController::class, 'exportExcel'])->name('purchase.excel');

Route::get('reports/purchases', [App\Http\Controllers\PurchaseReportController::class, 'index'])->name('reports.purchases.index');
Route::post('reports/purchases/show', [App\Http\Controllers\PurchaseReportController::class, 'show'])->name('purchases.report.show');
Route::get('export/report/purchase/excel', [App\Http\Controllers\PurchaseReportController::class, 'exportExcel'])
    ->name('purchase.report.excel');
Route::get('export/report/purchase/pdf', [App\Http\Controllers\PDFController::class, 'purchaseReportPDF'])
    ->name('purchase.report.pdf');
Route::get('reports/sale', [App\Http\Controllers\SalesReportController::class, 'index'])->name('reports.sales.index');
Route::post('reports/sale', [App\Http\Controllers\SalesReportController::class, 'show'])->name('sales.report.show');
Route::get('reports/sale/pdf', [App\Http\Controllers\PDFController::class, 'allSalesPDF'])->name('all.sales.pdf');
Route::get('reports/export/excel', [App\Http\Controllers\SalesInvoiceController::class, 'exportAllExcel'])->name('all.sales.excel');

Route::get('item/price/{id}', [App\Http\Controllers\ItemController::class, 'getItemPrice'])->name('item.price');



Route::resource('screens', App\Http\Controllers\ScreenController::class);


Route::resource('screenStatuses', App\Http\Controllers\ScreenStatusController::class);


Route::resource('reservations', App\Http\Controllers\ReservationsController::class);
Route::get('order/item/destroy', [App\Http\Controllers\ReservationsController::class, 'destroyItem'])->name('order.item.destroy');
Route::get('reservations/order/pdf', [App\Http\Controllers\PDFController::class, 'reservationsPDF'])->name('reservations.pdf');



Route::resource('orders', App\Http\Controllers\OrderController::class);


Route::resource('expenses', App\Http\Controllers\ExpenseController::class);
Route::post('expenses/search/date', [App\Http\Controllers\ExpenseController::class, 'expenseByDate'])->name('expenses.search');
Route::get('expenses/search/date', [App\Http\Controllers\ExpenseController::class, 'expenseByDate'])->name('expenses.search');

app/Models/PurchaseInvoice.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class PurchaseInvoice
 * @package App\Models
 * @version January 5, 2022, 10:47 am UTC
 *
 * @property string $date
 * @property number $provider_id
 * @property string $type
 */
class PurchaseInvoice extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'purchase_invoices';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'invoice_id',
        'provider_id',
        'type',
        'quantity',
        'total'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'invoice_id' => 'date',
        'type' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'provider_id' => 'required',
        'type' => 'required'
    ];

    public function provider()
    {
        return $this->belongsTo(Provider::class);
    }
    public function items()
    {
        return $this->belongsToMany(Item::class, 'item_purchase_invoice', 'invoice_id','item_id')
            ->withPivot('quantity', 'purchasing_price', 'total' , 'id');
    }

     protected static function boot()
    {
        parent::boot();
        static::deleting(function ($purchaseInvoice){
            $purchaseInvoice->items()->detach();

        });
    }


}

app/Http/Controllers/PurchaseInvoiceController.php
<?php

namespace App\Http\Controllers;

use App\Exports\PurchaseExport;
use App\Http\Requests\CreatePurchaseInvoiceRequest;
use App\Http\Requests\UpdatePurchaseInvoiceRequest;
use App\Repositories\PurchaseInvoiceRepository;
use App\Http\Controllers\AppBaseController;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Auth;
use App\Models\Item;
use App\Models\Provider;
use App\Models\PurchaseInvoice;
use Illuminate\Http\Request;
use Carbon\Carbon;
use Flash;
use Response;
use DB;

class PurchaseInvoiceController extends AppBaseController
{
    /** @var  PurchaseInvoiceRepository */
    private $purchaseInvoiceRepository;

    public function __construct(PurchaseInvoiceRepository $purchaseInvoiceRepo)
    {
        $this->purchaseInvoiceRepository = $purchaseInvoiceRepo;
    }

    /**
     * Display a listing of the PurchaseInvoice.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        if (Auth::check())
        {
        $purchaseInvoices = $this->purchaseInvoiceRepository->all();
        $providers = Provider::all()->pluck('name', 'id');

        return view('purchase_invoices.index')
            ->with(['purchaseInvoices'=>$purchaseInvoices , 'providers'=>$providers]);
        }
        else{
            return Redirect::to('/login');
        }
    }

    /**
     * Show the form for creating a new PurchaseInvoice.
     *
     * @return Response
     */
    public function create()
    {
        if (Auth::check())
        {
        $providers=Provider::all()->pluck('name','id');
        $items=Item::all();
        return view('purchase_invoices.create')->with(['providers'=>$providers , 'items'=>$items]);
        }
        else{
            return Redirect::to('/login');
        }
    }

    /**
     * Store a newly created PurchaseInvoice in storage.
     *
     * @param CreatePurchaseInvoiceRequest $request
     *
     * @return Response
     */
    public function store(CreatePurchaseInvoiceRequest $request)
    {
        if (Auth::check())
        {
        $input = $request->all();
        $items=$input['item_id'];
        $itemId=[];
        foreach($items  as $item)
        {
            $id=Item::where('item_number',$item)->first()->id;
            array_push($itemId,$id);

        }

        $arraySize = count($input['item_id']);
        DB::beginTransaction();
        try {

            $purchaseInvoice = PurchaseInvoice::create([
                'invoice_id' => Carbon::now()->toDateString(),
                'provider_id'=>$input['provider_id'],
                'type'=>$input['type'],
                'quantity' => $input['allQuantity'],
                'total' => $input['allTotal'] ]);

                $total = $input['total'];
                $quantity = $input['qty'];
                $price = $input['price'];

            for ($i = 0; $i < $arraySize; $i++) {
                $purchaseInvoice->items()->attach(
                    $itemId[$i], [
                        'quantity' => $quantity[$i],
                        'purchasing_price' => $price[$i],
                        'total' => $total[$i]

                    ]
                );

            }
                DB::commit();
                Flash::success('purchase Invoice saved successfully.');

                return redirect(route('purchaseInvoices.index'));
        }
        catch (\Exception $e) {
            dd($e);
            DB::rollback();
            Flash::error('Created failed');
            return redirect(route('purchaseInvoices.index'));

        }
    }
    else{
        return Redirect::to('/login');
    }

    }

    /**
     * Display the specified PurchaseInvoice.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        if (Auth::check())
        {
        $purchaseInvoice = PurchaseInvoice::with('items')->where('id', $id)->get()->first();
        if (empty($purchaseInvoice)) {
            Flash::error('Purchase Invoice not found');

            return redirect(route('purchaseInvoices.index'));
        }

        return view('purchase_invoices.show')->with('purchaseInvoice', $purchaseInvoice);
    }
    else{
        return Redirect::to('/login');
    }
    }

    /**
     * Show the form for editing the specified PurchaseInvoice.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        if (Auth::check())
        {
        $purchaseInvoice = $this->purchaseInvoiceRepository->find($id);
        $providers = Provider::all()->pluck('name', 'id');
        $items=Item::all();

        if (empty($purchaseInvoice)) {
            Flash::error('Purchase Invoice not found');

            return redirect(route('purchaseInvoices.index'));
        }

        return view('purchase_invoices.edit')->with(
            ['purchaseInvoice'=> $purchaseInvoice , 'providers'=>$providers,
            'items'=>$items]);
        }
        else{
            return Redirect::to('/login');
        }
    }

    /**
     * Update the specified PurchaseInvoice in storage.
     *
     * @param int $id
     * @param UpdatePurchaseInvoiceRequest $request
     *
     * @return Response
     */
    public function update($id, UpdatePurchaseInvoiceRequest $request)
    {
        if (Auth::check())
        {
        $purchaseInvoice = $this->purchaseInvoiceRepository->find($id);
        $input=$request->all();

        DB::beginTransaction();
        try {
            $purchaseInvoice = $this->purchaseInvoiceRepository->update([
                'provider_id'=>$input['provider_id'],
                'type'=>$input['type'],
                'quantity' => $input['allQuantity'],
                'total' => $input['allTotal']
                ], $id);

            if($request->newItemId)
            {
                $items=$input['newItemId'];
                $newItemId=[];
                foreach($items  as $item)
                {
                    $id=Item::where('item_number',$item)->first()->id;
                    array_push($newItemId,$id);

                }
                $newCount=count($newItemId);
                $newPrice=$input['newPrice'];
                $newQty=$input['newQty'];
                $newTotal=$input['newTotal'];

                for ($i = 0; $i < $newCount; $i++) {
                    $purchaseInvoice->items()->attach(
                        $newItemId[$i], [
                            'quantity' => $newQty[$i],
                            'purchasing_price' => $newPrice[$i],
                            'total' => $newTotal[$i]
                        ]);
            }
            }

            if($request->item_id)
            {
                $total = $input['total'];
                $quantity = $input['qty'];
                $price = $input['price'];
                $itemId = $input['item_id'];
                $arraySize = count($input['item_id']);
                $pivotId=$input['pivotId'];

                for($i=0 ; $i<$arraySize ; $i++)
                {
                    $purchaseInvoice->items()->wherePivot('id',$pivotId[$i])->updateExistingPivot($itemId[$i], [
                        'quantity' => $quantity[$i],
                        'purchasing_price' => $price[$i],
                        'total' => $total[$i]
                    ], false);

                }

            }


                DB::commit();
                Flash::success('purchase Invoice update successfully.');

                return redirect(route('purchaseInvoices.index'));
        }
        catch (\Exception $e) {
            dd($e);
            DB::rollback();
            Flash::error('update failed');
            return redirect(route('purchaseInvoices.index'));

        }



        Flash::success('Purchase Invoice updated successfully.');

        return redirect(route('purchaseInvoices.index'));
    }
    else{
        return Redirect::to('/login');
    }
    }

      /**
     * Remove the specified  item that belong PurchaseInvoice from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */

    public function destroyItem(Request $request)
    {
        if (Auth::check())
        {
        $input=$request->all();
        $purchaseInvoiceId = (int)$request->purchaseInvoiceId;
        $pivotId=$input['pivotId'];
        DB::beginTransaction();
        try {

            $item_id=$input['item_id'];
            $purchaseInvoice = $this->purchaseInvoiceRepository->find($purchaseInvoiceId);
            $item = $purchaseInvoice->items()->wherePivot('id',$pivotId)->detach($item_id);
            $total=0;
            $quantity=0;
            foreach($purchaseInvoice->items as $invoiceItem)
            {
                $total+=$invoiceItem->pivot['total'];
                $quantity+=$invoiceItem->pivot['quantity'];
            }
            $purchaseInvoice= $this->purchaseInvoiceRepository->update(['total'=>$total , 'quantity'=>$quantity], $purchaseInvoiceId);

        DB::commit();

        //Back to Update Fields
        $providers = Provider::all()->pluck('name', 'id');
        $items=Item::all();
        Flash::success('Item Removed from Purchase Invoice successfully.');

        return view('purchase_invoices.edit')->with([
            'purchaseInvoice' => $purchaseInvoice,
            'providers' => $providers, 'items' => $items
        ]);
        }
        catch (\Exception $e) {
            dd($e);
            DB::rollback();
            Flash::error('Deleted failed');
            return redirect(route('purchaseInvoices.index'));

        }
    }
    else{
        return Redirect::to('/login');
    }


    }

    /**
     * Remove the specified PurchaseInvoice from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {

resources/views/purchase_invoices/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('purchaseInvoices.index') !!}">Purchase Invoice</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Purchase Invoice</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'purchaseInvoices.store']) !!}

                                   @include('purchase_invoices.create_fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/purchase_invoices/create_fields.blade.php
<!-- Provider Id Field -->
<div class="form-group col-sm-4">
    {!! Form::label('provider_id', 'Provider Name:') !!}

    {!! Form::select('provider_id' ,$providers , null, ['class' => 'form-control selectpicker' , "size"=>'2','style'=>"width: 200px" , 'id'=>'select' ,'data-live-search'=>'true', 'data-show-subtext'=>'true' ]) !!}
</div>
<!-- Type Field -->
<div class="form-group col-sm-4">
    {!! Form::label('type', 'Invoice Type:') !!}
    <br>
    {{ Form::radio('type', 'Cash',['class'=>' form-control' ]) }}
    {!! Form::label('Cash', 'Cash') !!}
    {{ Form::radio('type', 'Credit', ['class'=>' form-control']) }}
    {!! Form::label('Credit', 'Credit') !!}
</div>
<table class="table table-striped" id="dataTable">
    <thead>
        <tr>
            <th>Item Name</th>
            <th>Quantity</th>
            <th>Price/pices</th>
            <th>Total</th>
            <th>
            <button type="button"  class="btn btn-ghost-danger"   style="width:50px;" onclick="deleteRow()"><i class="fas fa-minus"></i></button>

            </th>
        </tr>
        </thead>
<tbody>

    <tr id='row_1'>
        <p>
            <td>
                <div class="form-group col-sm-12">
                    <input list="item_id" name="item_id[]" class="form-control form-select" style="width:200px;" placeholder="search item" />
                    <datalist id="item_id" >
                        @foreach ( $items as $item )
                        <option  value="{{ $item['item_number'] }}">{{ $item['name'] }}</option>
                        @endforeach
                    </datalist>
                </div>

            </td>
            <td>
                <div class="form-group col-sm-12">
                <input type="number" class="form-control" required="required" id='qty[row_1]' name="qty[]" oninput="calculate()" onChange="updateCalculate(1)"  min="0">
                </div>
            </td>
            <td>
                <div class="form-group col-sm-12">
                <input type="number" required="required" class="form-control " id = 'price[row_1]' name="price[]" oninput="calculate()" onChange="updateCalculate(1)"  step="0.01" min=0>
                </div>
            </td>

            <td>
                <div class="form-group col-sm-12">
                <input type="text" required="required" class="form-control lst " id ='total[row_1]' name="total[]" readonly>
                </div>
            </td>
        </p>
    </tr>
</tbody>
</table>
<div class="form-group form-inline col-sm-5 float-right">
    {{-- <label ><b>All Qyantity : </b> </label> --}}
    <input type="hidden" readonly class="form-control ml-3 " id ='allQuantity' name="allQuantity">
</br>
    <h6 class="pt-3"><b>Total Balance :</b></h6>
    <input type="text" readonly class="form-control pt-3 ml-2" id ='allTotal' name="allTotal">
    </div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('purchaseInvoices.index') }}" class="btn btn-secondary">Cancel</a>
</div>


<script language="javascript">
var myTotal =0;
var myQuantity =0;
var total=0;

function calculate() {
    var rowCount = $('#dataTable tr').length-1;
    var myBox1 = document.getElementById('qty[row_'+rowCount+']').value;
    var myBox2 = document.getElementById('price[row_'+rowCount+']').value;
    var total = document.getElementById('total[row_'+rowCount+']');
    var myResult1 = myBox1 * myBox2 ;
    total.value = myResult1;
    totalAll(total);
    if(myBox2){
        quantityAll(myBox1);
    }

}

function totalAll(total) {

    myTotal = Number(myTotal) + Number(total.value);
    var allTotal = document.getElementById('allTotal');
    allTotal.value = myTotal;



}

function quantityAll(qty) {

    myQuantity = Number(myQuantity) + Number(qty);
    var allQuantity = document.getElementById('allQuantity');
    allQuantity.value = myQuantity;



}
</script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<script language="javascript">

var myTotal =0;
var myQuantity =0;
var row=0;
var total=0;
$(document).on('keyup', '.lst', function(e) {
    var rowCount = $('#dataTable tr').length;
  var code = (e.keyCode ? e.keyCode : e.which);
  row=rowCount-1;
  var total = document.getElementById('total[row_'+row+']').value;

  if (code == 13 && total && total !=0) {
    var table = document.getElementById("dataTable");
    var row = table.insertRow(rowCount);
    var cell1 = row.insertCell(0);
    var cell2 = row.insertCell(1);
    var cell3 = row.insertCell(2);
    var cell4 = row.insertCell(3);
    var qty = '[row_'.concat(rowCount,']');
    var price = '[row_'.concat(rowCount,']');
    var total = '[row_'.concat(rowCount,']');
    var abc = 'this is text'; <?php $abc = "<script>document.write(rowCount)</script>"?>
    cell1.innerHTML='<div class="form-group col-sm-12"><input list="item_id" name="item_id[]" class="form-control form-select" placeholder="search item" style="width:200px;" />';
    cell1.innerHTML+='<datalist id="item_id" >@foreach ( $items as $item )<option  value="{{ $item['item_number'] }}">{{ $item['name'] }}</option>@endforeach </datalist></div>';
    cell2.innerHTML = '<div class="form-group col-sm-12"><input type="text" class="form-control"  name="qty[]"  id="qty[row_'+rowCount+']" oninput="calculate()" onChange="updateCalculate('+rowCount+')"  min="0"></div>';
    cell3.innerHTML = '<div class="form-group col-sm-12"><input type="text" class="form-control"  name="price[]"  id="price[row_'+rowCount+']" oninput="calculate()" onChange="updateCalculate('+rowCount+')"  step="0.01" min=0></div>';
    cell4.innerHTML = '<div class="form-group col-sm-12"><input type="text"   class="form-control lst" name="total[]" id="total[row_'+rowCount+']" readonly></div>';
    $(this).focus().select();
    rowCount++;
  }
});

$(document).on('keydown', '.inputs', function(e) {
  var code = (e.keyCode ? e.keyCode : e.which);
  if (code == 13) {
    var index = $('.inputs').index(this) + 1;
    $('.inputs').eq(index).focus();
  }
});

function deleteRow() {
    var rowCount = $('#dataTable tr').length;
    var row=rowCount-1;

    if(row > 1)
    {
        document.getElementById("dataTable").deleteRow(rowCount-1);
        var newRow=row-1;
        updateCalculate(newRow);

    }
    if(row==1)
    {
        alert("the minimum number of rows should be 1. ");
    }
}

function updateCalculate(newRow) {
    var row=newRow;
    var myBox1 = document.getElementById('qty[row_'+row+']').value;
    var myBox2 = document.getElementById('price[row_'+row+']').value;
    var total = document.getElementById('total[row_'+row+']');
    var myResult1 = myBox1 * myBox2 ;
    total.value = myResult1;
    updateQuantityAll();
    updateTotalAll();
}

function updateQuantityAll() {

var allQty = document.getElementById('allQuantity');
var rowCount = $('#dataTable tr').length-1;
var sum =0;
for (var i =1; i <=rowCount; i++) {
    var qty = document.getElementById('qty[row_'+i+']').value;
    sum = Number(sum)+ Number(qty) ;
    allQty.value = Number(sum);
}


}

function  updateTotalAll() {

var allTotal = document.getElementById('allTotal');
var rowCount = $('#dataTable tr').length-1;
var sum =0;
for (var i =1; i <=rowCount; i++) {
    var qty = document.getElementById('total[row_'+i+']').value;
    sum = Number(sum)+ Number(qty) ;
    allTotal.value = Number(sum);

}
}

</script>

resources/views/purchase_invoices/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('purchaseInvoices.index') !!}">Purchase Invoice</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
            @include('flash::message')
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Purchase Invoice</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($purchaseInvoice, ['route' => ['purchaseInvoices.update', $purchaseInvoice->id], 'method' => 'patch']) !!}

                              @include('purchase_invoices.update_fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/purchase_invoices/excel.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Purchase Invoices</title>
</head>
<style>
    table, td, th {
      border: 1px solid #ddd;
      text-align: center;
      font-size: smaller;    }

    table {
      border-collapse: collapse;
      width: 100%;
    }

    th, td {
      padding: 15px;
    }
    h1,img{
        font-size: medium;
        text-align: center;

    }
    .img-contanier{
        text-align: center;
    }
    </style>
<body>

    <div class="table-responsive">
        <h1>Purchase Invoices </h1>
            <table border="5px" bordercolor="#8707B0">
                <thead>
                    <tr>
                    <th><b>Invoice Number</b></th>
                    <th><b>Date</b></th>
                    <th><b>Type</b></th>
                    <th><b>Provider Name</b></th>
                    <th class="text-center"><b>Purchase Details</b></th>
                    </tr>
                    </thead>
                <tbody>
                    @foreach($purchaseInvoices as $purchaseInvoice)
                    <tr>
                    <td>{{ $purchaseInvoice->id }}</td>
                    <td><?php echo(date_format($purchaseInvoice->invoice_id, 'Y-m-d')); ?></td>
                    <td>{{ $purchaseInvoice->type }}</td>
                    <td>{{ $purchaseInvoice->provider->name }}</td>
                    <td>
            <table border="1px" bordercolor="#F35557">

            <thead>
                <tr>
                <th><b>Name</b></th>
                <th><b>Quantity</b></th>
                <th><b>Price/pcs</b></th>
                <th><b>Total</b></th>
                </tr>
                </thead>
                @foreach($purchaseInvoice->items as $purchaseItem)
                <tr>
                    @foreach($items as $item)
                    @if($purchaseItem->id == $item->id )
                    <td class="text-xs">{{ $item->name }}  </td>




                <td class="text-xs">  {{$purchaseItem->pivot['quantity']}}</td>
                <td class="text-xs">  {{$purchaseItem->pivot['purchasing_price']}}</td>
                <td class="text-xs">  {{$purchaseItem->pivot['total']}}</td>
                @endif

                @endforeach

            </tr>

            @endforeach
        </table>
    </td>

    </tr>
       @endforeach
</tbody>
</table>
</div>
<p style="text-align:right;"><b>Total Balance: {{ $purchaseInvoice->total }} JD</b></p>

</body>
</html>

resources/views/purchase_invoices/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Purchase Invoices</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             PurchaseInvoices
                             <a class="pull-right" href="{{ route('purchaseInvoices.create') }}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('purchase_invoices.table')
                              <div class="pull-right mr-3">

                              </div>


                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/purchase_invoices/table.blade.php
<div class="table-responsive-sm">
    <table class="table table-striped" id="purchaseInvoices-table">
        <thead>
        <tr>
        <th>#</th>
        <th>Date</th>
        <th>Invoice Id</th>
        <th>Provider Name</th>
        <th>Type</th>
        <th>Quantity</th>
        <th>Total</th>
        <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($purchaseInvoices as $key => $purchaseInvoice)
            <tr>
            <td>{{ $key+1 }}</td>
            <td><?php echo(date_format($purchaseInvoice->invoice_id, 'Y-m-d')); ?></td>
            <td>{{ $purchaseInvoice->invoice_id->format('dmy') }}</td>
            <td>{{ $purchaseInvoice->provider->name }}</td>
            <td>{{ $purchaseInvoice->type }}</td>
            <td>{{ $purchaseInvoice->quantity }}</td>
            <td>{{ $purchaseInvoice->total }}</td>
                <td>
                    {!! Form::open(['route' => ['purchaseInvoices.destroy', $purchaseInvoice->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('purchaseInvoices.show', [$purchaseInvoice->id]) }}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                        <a href="{{ route('purchaseInvoices.edit', [$purchaseInvoice->id]) }}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>