routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/register', function () {
    return view('auth.login');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');


Route::resource('items', App\Http\Controllers\ItemController::class);


Route::resource('providers', App\Http\Controllers\ProviderController::class);


Route::resource('purchaseInvoices', App\Http\Controllers\PurchaseInvoiceController::class);


Route::resource('salesInvoices', App\Http\Controllers\SalesInvoiceController::class);

Route::get('sales/pdf', [App\Http\Controllers\PDFController::class, 'salesPDF'])->name('sales.pdf');
Route::get('sales/item/destroy', [App\Http\Controllers\SalesInvoiceController::class, 'destroyItem'])->name('sales.item.destroy');


Route::get('purchase/pdf', [App\Http\Controllers\PDFController::class, 'purchasePDF'])->name('purchase.pdf');
Route::get('purchaseinvoice/item/destroy', [App\Http\Controllers\PurchaseInvoiceController::class, 'destroyItem'])->name('purchase.item.destroy');
Route::get('export/excel', [App\Http\Controllers\SalesInvoiceController::class, 'exportExcel'])->name('sales.excel');
Route::get('export/purchase/excel', [App\Http\Controllers\PurchaseInvoiceController::class, 'exportExcel'])->name('purchase.excel');

Route::get('reports/purchases', [App\Http\Controllers\PurchaseReportController::class, 'index'])->name('reports.purchases.index');
Route::post('reports/purchases/show', [App\Http\Controllers\PurchaseReportController::class, 'show'])->name('purchases.report.show');
Route::get('export/report/purchase/excel', [App\Http\Controllers\PurchaseReportController::class, 'exportExcel'])
    ->name('purchase.report.excel');
Route::get('export/report/purchase/pdf', [App\Http\Controllers\PDFController::class, 'purchaseReportPDF'])
    ->name('purchase.report.pdf');
Route::get('reports/sale', [App\Http\Controllers\SalesReportController::class, 'index'])->name('reports.sales.index');
Route::post('reports/sale', [App\Http\Controllers\SalesReportController::class, 'show'])->name('sales.report.show');
Route::get('reports/sale/pdf', [App\Http\Controllers\PDFController::class, 'allSalesPDF'])->name('all.sales.pdf');
Route::get('reports/export/excel', [App\Http\Controllers\SalesInvoiceController::class, 'exportAllExcel'])->name('all.sales.excel');

Route::get('item/price/{id}', [App\Http\Controllers\ItemController::class, 'getItemPrice'])->name('item.price');



Route::resource('screens', App\Http\Controllers\ScreenController::class);


Route::resource('screenStatuses', App\Http\Controllers\ScreenStatusController::class);


Route::resource('reservations', App\Http\Controllers\ReservationsController::class);
Route::get('order/item/destroy', [App\Http\Controllers\ReservationsController::class, 'destroyItem'])->name('order.item.destroy');
Route::get('reservations/order/pdf', [App\Http\Controllers\PDFController::class, 'reservationsPDF'])->name('reservations.pdf');



Route::resource('orders', App\Http\Controllers\OrderController::class);


Route::resource('expenses', App\Http\Controllers\ExpenseController::class);
Route::post('expenses/search/date', [App\Http\Controllers\ExpenseController::class, 'expenseByDate'])->name('expenses.search');
Route::get('expenses/search/date', [App\Http\Controllers\ExpenseController::class, 'expenseByDate'])->name('expenses.search');

resources/views/screen_statuses/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('screenStatuses.index') !!}">Screen Status</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Screen Status</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'screenStatuses.store']) !!}

                                   @include('screen_statuses.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/screen_statuses/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('screenStatuses.index') !!}">Screen Status</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Screen Status</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($screenStatus, ['route' => ['screenStatuses.update', $screenStatus->id], 'method' => 'patch']) !!}

                              @include('screen_statuses.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/screen_statuses/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('screenStatuses.index') }}" class="btn btn-secondary">Cancel</a>
</div>

resources/views/screen_statuses/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Screen Statuses</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             ScreenStatuses
                             <a class="pull-right" href="{{ route('screenStatuses.create') }}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('screen_statuses.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/screen_statuses/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('screenStatuses.index') }}">Screen Status</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('screenStatuses.index') }}" class="btn btn-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('screen_statuses.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/screen_statuses/show_fields.blade.php
<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{{ $screenStatus->name }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $screenStatus->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $screenStatus->updated_at }}</p>
</div>

resources/views/screen_statuses/table.blade.php
<div class="table-responsive-sm">
    <table class="table table-striped" id="screenStatuses-table">
        <thead>
            <tr>
                <th>Name</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($screenStatuses as $screenStatus)
            <tr>
                <td>{{ $screenStatus->name }}</td>
                <td>
                    {!! Form::open(['route' => ['screenStatuses.destroy', $screenStatus->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('screenStatuses.show', [$screenStatus->id]) }}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                        <a href="{{ route('screenStatuses.edit', [$screenStatus->id]) }}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>