routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/register', function () {
    return view('auth.login');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');


Route::resource('items', App\Http\Controllers\ItemController::class);


Route::resource('providers', App\Http\Controllers\ProviderController::class);


Route::resource('purchaseInvoices', App\Http\Controllers\PurchaseInvoiceController::class);


Route::resource('salesInvoices', App\Http\Controllers\SalesInvoiceController::class);

Route::get('sales/pdf', [App\Http\Controllers\PDFController::class, 'salesPDF'])->name('sales.pdf');
Route::get('sales/item/destroy', [App\Http\Controllers\SalesInvoiceController::class, 'destroyItem'])->name('sales.item.destroy');


Route::get('purchase/pdf', [App\Http\Controllers\PDFController::class, 'purchasePDF'])->name('purchase.pdf');
Route::get('purchaseinvoice/item/destroy', [App\Http\Controllers\PurchaseInvoiceController::class, 'destroyItem'])->name('purchase.item.destroy');
Route::get('export/excel', [App\Http\Controllers\SalesInvoiceController::class, 'exportExcel'])->name('sales.excel');
Route::get('export/purchase/excel', [App\Http\Controllers\PurchaseInvoiceController::class, 'exportExcel'])->name('purchase.excel');

Route::get('reports/purchases', [App\Http\Controllers\PurchaseReportController::class, 'index'])->name('reports.purchases.index');
Route::post('reports/purchases/show', [App\Http\Controllers\PurchaseReportController::class, 'show'])->name('purchases.report.show');
Route::get('export/report/purchase/excel', [App\Http\Controllers\PurchaseReportController::class, 'exportExcel'])
    ->name('purchase.report.excel');
Route::get('export/report/purchase/pdf', [App\Http\Controllers\PDFController::class, 'purchaseReportPDF'])
    ->name('purchase.report.pdf');
Route::get('reports/sale', [App\Http\Controllers\SalesReportController::class, 'index'])->name('reports.sales.index');
Route::post('reports/sale', [App\Http\Controllers\SalesReportController::class, 'show'])->name('sales.report.show');
Route::get('reports/sale/pdf', [App\Http\Controllers\PDFController::class, 'allSalesPDF'])->name('all.sales.pdf');
Route::get('reports/export/excel', [App\Http\Controllers\SalesInvoiceController::class, 'exportAllExcel'])->name('all.sales.excel');

Route::get('item/price/{id}', [App\Http\Controllers\ItemController::class, 'getItemPrice'])->name('item.price');



Route::resource('screens', App\Http\Controllers\ScreenController::class);


Route::resource('screenStatuses', App\Http\Controllers\ScreenStatusController::class);


Route::resource('reservations', App\Http\Controllers\ReservationsController::class);
Route::get('order/item/destroy', [App\Http\Controllers\ReservationsController::class, 'destroyItem'])->name('order.item.destroy');
Route::get('reservations/order/pdf', [App\Http\Controllers\PDFController::class, 'reservationsPDF'])->name('reservations.pdf');



Route::resource('orders', App\Http\Controllers\OrderController::class);


Route::resource('expenses', App\Http\Controllers\ExpenseController::class);
Route::post('expenses/search/date', [App\Http\Controllers\ExpenseController::class, 'expenseByDate'])->name('expenses.search');
Route::get('expenses/search/date', [App\Http\Controllers\ExpenseController::class, 'expenseByDate'])->name('expenses.search');

app/Models/SalesInvoice.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use DB;

/**
 * Class SalesInvoice
 * @package App\Models
 * @version January 5, 2022, 10:52 am UTC
 *
 * @property string $id
 */
class SalesInvoice extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'sales_invoices';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'invoice_id',
        'quantity',
        'total'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'invoice_id' => 'date'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        // 'id' => 'required'
    ];

    public function items()
    {
        return $this->belongsToMany(Item::class, 'item_sales_invoice', 'invoice_id' , 'item_id')
            ->withPivot('quantity', 'sale_price', 'total','id');
    }

    protected static function boot()
    {
        parent::boot();
        static::deleting(function ($saleInvoice){
            $saleInvoice->items()->detach();

        });
    }

    public static function getEmployee($id){

        // $salesInvoice=SalesInvoice::select('invoice_id','quantity','total')->where('id',$id )
        // ->with('items')->get();
        // $salesInvoices = SalesInvoice::with('items')->select('invoice_id','quantity','total')->where('id',$id )->get();


        // dd($salesInvoices);
        return DB::table('inmuebles_personas')->get();


        return $salesInvoice;
    }

}

app/Http/Controllers/SalesInvoiceController.php
<?php

namespace App\Http\Controllers;

use App\Exports\SalesExport;
use App\Http\Requests\CreateSalesInvoiceRequest;
use App\Http\Requests\UpdateSalesInvoiceRequest;
use App\Repositories\SalesInvoiceRepository;
use App\Http\Controllers\AppBaseController;
use Maatwebsite\Excel\Facades\Excel;
use App\Exports\AllSalesExport;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Auth;
use App\Models\Item;
use App\Models\SalesInvoice;
use Illuminate\Http\Request;
use Carbon\Carbon;
use Flash;
use Response;
use DB;

class SalesInvoiceController extends AppBaseController
{
    /** @var  SalesInvoiceRepository */
    private $salesInvoiceRepository;

    public function __construct(SalesInvoiceRepository $salesInvoiceRepo)
    {
        $this->salesInvoiceRepository = $salesInvoiceRepo;
    }

    /**
     * Display a listing of the SalesInvoice.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        if (Auth::check()) {

        $salesInvoices = SalesInvoice::with('items')->get();

        return view('sales_invoices.index')
            ->with('salesInvoices', $salesInvoices);
        }
        else{
            return Redirect::to('/login');
        }
    }

    /**
     * Show the form for creating a new SalesInvoice.
     *
     * @return Response
     */
    public function create()
    {
        if (Auth::check()) {

        $items = Item::all();
        $invoice_id =  Carbon::now()->toDateString();
        $formType = 'create';

        return view('sales_invoices.create')->with(['items' => $items, 'invoice_id' => $invoice_id , 'formType' =>$formType]);
        }
        else{
            return Redirect::to('/login');
        }
    }

    /**
     * Store a newly created SalesInvoice in storage.
     *
     * @param CreateSalesInvoiceRequest $request
     *
     * @return Response
     */
    public function store(CreateSalesInvoiceRequest $request)
    {
        if (Auth::check()) {
        $input = $request->all();
        $items=$input['item_id'];
        $itemId=[];
        foreach($items  as $item)
        {
            $id=Item::where('item_number',$item)->first()->id;
            array_push($itemId,$id);

        }
        $arraySize = count($input['item_id']);

        DB::beginTransaction();
        try {

            $salesInvoice = SalesInvoice::create([
                'invoice_id' => $input['date'],
                 'quantity' => $input['allQyantity'],
                'total' => $input['allTotal'] ]);

                $total = $input['total'];
                $quantity = $input['qty'];
                $price = $input['price'];

            for ($i = 0; $i < $arraySize; $i++) {
                $salesInvoice->items()->attach(
                    $itemId[$i], [
                        'quantity' => $quantity[$i],
                        'sale_price' => $price[$i],
                        'total' => $total[$i]

                    ]
                );

            }
                DB::commit();
                Flash::success('Sales Invoice saved successfully.');

                return redirect(route('salesInvoices.index'));
        } catch (\Exception $e) {
            DB::rollback();
            Flash::error('Created failed'.$e);
            return redirect(route('salesInvoices.index'));

        }
    }
    else{
        return Redirect::to('/login');
    }
}

    /**
     * Display the specified SalesInvoice.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        if (Auth::check()) {
        $salesInvoice = $this->salesInvoiceRepository->find($id);

        if (empty($salesInvoice)) {
            Flash::error('Sales Invoice not found');

            return redirect(route('salesInvoices.index'));
        }
        $items = Item::all();
        $invoice_id = SalesInvoice::select('invoice_id')->where('id',$id)->first()['invoice_id'];

        return view('sales_invoices.show')->with(['salesInvoice' => $salesInvoice ,'items' => $items ,'invoice_id' => $invoice_id]);
    }
    else{
        return Redirect::to('/login');
    }
}

    /**
     * Show the form for editing the specified SalesInvoice.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        if (Auth::check()) {
        $salesInvoice = $this->salesInvoiceRepository->find($id);

        if (empty($salesInvoice)) {
            Flash::error('Sales Invoice not found');

            return redirect(route('salesInvoices.index'));
        }
        $items = Item::all();
        $invoice_id = SalesInvoice::select('invoice_id')->where('id',$id)->first()['invoice_id'];


        return view('sales_invoices.edit')->with(['salesInvoice' => $salesInvoice ,'items' => $items ,'invoice_id' => $invoice_id]);
    }
    else{
        return Redirect::to('/login');
    }
}

    /**
     * Update the specified SalesInvoice in storage.
     *
     * @param int $id
     * @param UpdateSalesInvoiceRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateSalesInvoiceRequest $request)
    {
        if (Auth::check()) {
        $salesInvoice = SalesInvoice::find($id)->first();

        if (empty($salesInvoice)) {
            Flash::error('Sales Invoice not found');

            return redirect(route('salesInvoices.index'));
        }
        DB::beginTransaction();
        try {

            $salesInvoice = $this->salesInvoiceRepository->update([
                'invoice_id' => $request['date'],
                'quantity' => $request['allQyantity'],
                'total' => $request['allTotal']
            ], $id);

            if($request['newItemId']){
                $newArraySize = count($request['newItemId']);
                $newTotal = $request['newTotal'];
                $newQty = $request['newQty'];
                $newPrice = $request['newPrice'];
                $items=$request['newItemId'];
                $newItemId=[];
                foreach($items  as $item)
                {
                    $id=Item::where('item_number',$item)->first()->id;
                    array_push($newItemId,$id);

                }

            for ($i = 0; $i < $newArraySize; $i++) {
                $salesInvoice->items()->attach(
                    $newItemId[$i], [
                        'quantity' => $newQty[$i],
                        'sale_price' => $newPrice[$i],
                        'total' => $newTotal[$i]

                    ]);
            }
            }
            if($request['item_id']){
            $total = $request['total'];
            $quantity = $request['qty'];
            $price = $request['price'];
            $itemId = $request['item_id'];
            $pivotId = $request['pivotId'];
            $arraySize = count($request['item_id']);
        for ($i = 0; $i < $arraySize; $i++) {
            $salesInvoice->items()->wherePivot('id',$pivotId[$i])->updateExistingPivot(
             $itemId[$i], [
                    'quantity' => $quantity[$i],
                    'sale_price' => $price[$i],
                    'total' => $total[$i]
                ]
            );
        }
    }
                DB::commit();
                Flash::success('Sales Invoice updated successfully.');

                return redirect(route('salesInvoices.index'));
        } catch (\Exception $e) {
            dd($e);
            DB::rollback();
            Flash::error('Created failed');
            return redirect(route('salesInvoices.index'));

        }



    }
    else{
        return Redirect::to('/login');
    }
}
     /**
     * Remove the specified  item that belong PurchaseInvoice from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */

    public function destroyItem(Request $request)
    {
        if (Auth::check()) {
        $input=$request->all();
        $saleInvoiceId = (int)$request['salesInvoiceId'];
        $pivotId=$input['pivotId'];
        DB::beginTransaction();
        try {

            $item_id=$input['item_id'];
            $salesInvoice = $this->salesInvoiceRepository->find($saleInvoiceId);
            $item = $salesInvoice->items()->wherePivot('id',$pivotId)->detach($item_id);
            $total=0;
            $quantity=0;
            foreach($salesInvoice->items as $invoiceItem)
            {
                $total+=$invoiceItem->pivot['total'];
                $quantity+=$invoiceItem->pivot['quantity'];
            }
            $salesInvoice= $this->salesInvoiceRepository->update(['total'=>$total , 'quantity'=>$quantity], $saleInvoiceId);

        DB::commit();

        //Back to Update Fields
        $items = Item::all();
        $invoice_id =  Carbon::now()->toDateString();
        Flash::success('Item Removed from Sales Invoice successfully.');

        return view('sales_invoices.edit')->with(['salesInvoice' => $salesInvoice ,'items' => $items ,'invoice_id' => $invoice_id]);
        }
        catch (\Exception $e) {
            dd($e);
            DB::rollback();
            Flash::error('Deleted failed');
            return redirect(route('salesInvoices.index'));

        }


    }
    else{
        return Redirect::to('/login');
    }
}

    /**
     * Remove the specified SalesInvoice from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        if (Auth::check()) {
        $salesInvoice = $this->salesInvoiceRepository->find($id);

        if (empty($salesInvoice)) {
            Flash::error('Sales Invoice not found');

            return redirect(route('salesInvoices.index'));
        }

        $this->salesInvoiceRepository->delete($id);

        Flash::success('Sales Invoice deleted successfully.');

        return redirect(route('salesInvoices.index'));
    }
    else{
        return Redirect::to('/login');
    }
}

resources/views/sales_invoices/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('salesInvoices.index') !!}">Sales Invoice</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Sales Invoice</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'salesInvoices.store']) !!}

                                   @include('sales_invoices.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/sales_invoices/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('salesInvoices.index') !!}">Sales Invoice</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Sales Invoice</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($salesInvoice, ['route' => ['salesInvoices.update', $salesInvoice->id], 'method' => 'patch']) !!}

                              @include('sales_invoices.update_fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/sales_invoices/excel.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Purchase Invoices</title>
</head>
<style>
    table, td, th {
      border: 1px solid #ddd;
      text-align: left;
      font-size: smaller;    }

    table {
      border-collapse: collapse;
      width: 100%;
    }

    th, td {
      padding: 15px;
    }
    h1,img{
        font-size: medium;
        text-align: center;

    }
    .img-contanier{
        text-align: center;
    }
    </style>
<body>

    <div class="table-responsive">
        <h1>Sales Invoices </h1>
        <h5>    {{ $date->format('d-m-20y') }}</h5>
            <table border="5px" bordercolor="#8707B0">
                <thead>
                    <tr>
                    <th><b> Invoice Number</b></th>
                    <th class="text-center">Sales Details</th>
                    </tr>
                    </thead>
                <tbody>
                    @foreach($salesInvoices as $salesInvoice)
                    <tr>
                    <td>{{ $salesInvoice->invoice_id->format('dmy') }}</td>
                    <td>
            <table border="1px" bordercolor="#F35557">

            <thead>
                <tr>
                <th><b>Item Name</b></th>
                <th><b>Quantity</b></th>
                <th><b>Price/pcs</b></th>
                <th><b>Total</b></th>
                </tr>
                </thead>
                @foreach($salesInvoice->items as $salesItem)
                <tr>
                    @foreach($items as $item)
                    @if($salesItem->id == $item->id )
                    <td class="text-xs">{{ $item->name }}  </td>




                <td class="text-xs">  {{$salesItem->pivot['quantity']}}</td>
                <td class="text-xs">  {{$salesItem->pivot['sale_price']}}</td>
                <td class="text-xs">  {{$salesItem->pivot['total']}}</td>
                @endif

                @endforeach

            </tr>

            @endforeach
        </table>
    </td>

    </tr>
       @endforeach
</tbody>
</table>
</div>
<p><b>Total Balance: {{ $salesInvoice->total }} JD</b></p>

</body>
</html>

resources/views/sales_invoices/fields.blade.php
</HEAD>
<BODY>


<div class="form-inline col-sm-6">
    <label><b> Date : </b></label>
    <input type="date" required="required" class="form-control ml-1"   name="date" >
</div>
    <table class="table table-striped" id="dataTable">
        <thead>
            <tr>
                <th>Item Name</th>
                <th>Quantity</th>
                <th>Price/pices</th>
                <th>Total</th>
                <th>
                <button type="button"  class="btn btn-ghost-danger"   style="width:50px;" onclick="deleteRow()"><i class="fas fa-minus"></i></button>
                </th>
            </tr>
            </thead>
    <tbody>


        <tr id='row_1'>
            <p>
                <td>
                    <div class="form-group col-sm-12">
                        <input list="item_id" name="item_id[]" class="form-control form-select" style="width:200px;" placeholder="search item" />
                        <datalist id="item_id" >
                            @foreach ( $items as $item )
                            <option  value="{{ $item['item_number'] }}">{{ $item['name'] }}</option>
                            @endforeach
                        </datalist>
                    </div>
                </td>

                <td>
                    <div class="form-group col-sm-12">
                        <input type="number" class="form-control" required="required" id='qty[row_1]' name="qty[]" oninput="calculate()" onChange="updateCalculate(1)"  min="0" >
                    </div>
                </td>
                <td>
                    <div class="form-group col-sm-12">
                        <input type="text" required="required" class="form-control" id = 'price[row_1]' name="price[]" oninput="calculate()" onChange="updateCalculate(1)"  step="0.01" min=0>
                    </div>
                </td>
                <td>
                    <div class="form-group col-sm-12">
                    <input type="text" required="required" class="form-control lst" id ='total[row_1]' name="total[]" readonly >
                    </div>
                </td>
            </p>
        </tr>
    </tbody>
</table>

<div class="form-group form-inline col-sm-3 float-right">
    <input type="text" hidden readonly class="form-control ml-4 " id ='allQuantity' name="allQyantity">
</br>
    <h6 class="pt-3"><b>Total Balance :</b></h6>
    <input type="text" readonly class="form-control pt-3 ml-2" id ='allTotal' name="allTotal">
    </div>

<!-- Submit Field -->
<div class="form-group col-sm-12 pt-3">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('salesInvoices.index') }}" class="btn btn-secondary">Cancel</a>
</div>


<SCRIPT language="javascript">
    var myTotal =0;
    var myQuantity =0;
    var row=0;
    var total=0;

    function calculate() {
        var rowCount = $('#dataTable tr').length-1;
        var myBox1 = document.getElementById('qty[row_'+rowCount+']').value;
        var myBox2 = document.getElementById('price[row_'+rowCount+']').value;
        var total = document.getElementById('total[row_'+rowCount+']');
        var myResult1 = myBox1 * myBox2 ;
        total.value = myResult1;
        totalAll(total);
        if(myBox2){
            quantityAll(myBox1);
        }

    }

    function totalAll(total) {

        myTotal = Number(myTotal) + Number(total.value);
        var allTotal = document.getElementById('allTotal');
        allTotal.value = myTotal;



    }

    function quantityAll(qty) {


        myQuantity = Number(myQuantity) + Number(qty);
        var allQuantity = document.getElementById('allQuantity');
        allQuantity.value = myQuantity;




    }

    </script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<script language="javascript">


var row=0;
var total=0;
$(document).on('keyup', '.lst', function(e) {
    var rowCount = $('#dataTable tr').length;
  var code = (e.keyCode ? e.keyCode : e.which);
  row=rowCount-1;
  var total = document.getElementById('total[row_'+row+']').value;

  if (code == 13 && total && total !=0) {
    var table = document.getElementById("dataTable");
    var row = table.insertRow(rowCount);
    var cell1 = row.insertCell(0);
    var cell2 = row.insertCell(1);
    var cell3 = row.insertCell(2);
    var cell4 = row.insertCell(3);
    var qty = '[row_'.concat(rowCount,']');
    var price = '[row_'.concat(rowCount,']');
    var total = '[row_'.concat(rowCount,']');
    var abc = 'this is text'; <?php $abc = "<script>document.write(rowCount)</script>"?>
    cell1.innerHTML='<div class="form-group col-sm-12"><input list="item_id" name="item_id[]" class="form-control form-select" placeholder="search item" style="width:200px; height: 35px;" />';
    cell1.innerHTML+='<datalist id="item_id" >@foreach ( $items as $item )<option  value="{{ $item['item_number'] }}">{{ $item['name'] }}</option>@endforeach </datalist></div>';
    cell2.innerHTML = '<div class="form-group col-sm-12"><input type="text" class="form-control"  name="qty[]"  id="qty[row_'+rowCount+']" oninput="calculate()"  onChange="updateCalculate('+rowCount+')"  min="0" required></div>';
    cell3.innerHTML = '<div class="form-group col-sm-12"><input type="text" class="form-control"  name="price[]"  id="price[row_'+rowCount+']" oninput="calculate()"  onChange="updateCalculate('+rowCount+')"  step="0.01" min=0 required></div>';
    cell4.innerHTML = '<div class="form-group col-sm-12"><input type="text"   class="form-control lst" name="total[]" id="total[row_'+rowCount+']" readonly></div>';
    $(this).focus().select();
    rowCount++;
  }
});

$(document).on('keydown', '.inputs', function(e) {
  var code = (e.keyCode ? e.keyCode : e.which);
  if (code == 13) {
    var index = $('.inputs').index(this) + 1;
    $('.inputs').eq(index).focus();
  }
});

function deleteRow() {
    var rowCount = $('#dataTable tr').length;
    var row=rowCount-1;

    if(row > 1)
    {
        document.getElementById("dataTable").deleteRow(rowCount-1);
        var newRow=row-1;
        updateCalculate(newRow);
    }
    if(row==1)
    {
        alert("the minimum number of rows should be 1. ");
    }
}

function updateCalculate(newRow) {
    var row=newRow;
    var myBox1 = document.getElementById('qty[row_'+row+']').value;
    var myBox2 = document.getElementById('price[row_'+row+']').value;
    var total = document.getElementById('total[row_'+row+']');
    var myResult1 = myBox1 * myBox2 ;
    total.value = myResult1;
    updateQuantityAll();
    updateTotalAll();
}

function updateQuantityAll() {

var allQty = document.getElementById('allQuantity');
var rowCount = $('#dataTable tr').length-1;
var sum =0;
for (var i =1; i <=rowCount; i++) {
    var qty = document.getElementById('qty[row_'+i+']').value;
    sum = Number(sum)+ Number(qty) ;
    allQty.value = Number(sum);
}


}

function  updateTotalAll() {

var allTotal = document.getElementById('allTotal');
var rowCount = $('#dataTable tr').length-1;
var sum =0;
for (var i =1; i <=rowCount; i++) {
    var qty = document.getElementById('total[row_'+i+']').value;
    sum = Number(sum)+ Number(qty) ;
    allTotal.value = Number(sum);

}
}
</script>

resources/views/sales_invoices/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Sales Invoices</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             SalesInvoices
                             <a class="pull-right" href="{{ route('salesInvoices.create') }}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('sales_invoices.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/sales_invoices/table.blade.php
<div class="table-responsive-sm">
    <table class="table table-striped" id="salesInvoices-table">
        <thead>
            <tr>
                <th>#</th>
                <th>Invoice Id</th>
                <th>Quantity</th>
                <th>Total</th>


                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($salesInvoices as $key => $salesInvoice)
            <tr>
                <td>{{ $key+1 }}</td>
                <td>{{ $salesInvoice->invoice_id->format('dmy') }}</td>
                <td>{{ $salesInvoice->quantity }}</td>
                <td>{{$salesInvoice->total }}</td>


                <td>
                    {!! Form::open(['route' => ['salesInvoices.destroy', $salesInvoice->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('salesInvoices.show', [$salesInvoice->id]) }}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                        <a href="{{ route('salesInvoices.edit', [$salesInvoice->id]) }}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>